export const createOrderFakeData = {
  from_name: 'Văn Tú',
  from_phone: '0974255412',
  from_address: '60 Trường Sơn',
  from_ward_name: 'Phường 10',
  from_district_name: 'Quận Tân Bình',
  from_province_name: 'Hồ Chí Minh',
  pick_shift: [5],
  to_phone: '0968890960',
  to_name: 'Tú Tú',
  wardName: 'Phường Phước Bình',
  districtName: 'Thành Phố Thủ Đức',
  provinceName: 'Hồ Chí Minh',
  to_address: '72 Thành Thái',
  to_district_id: '3695',
  to_ward_code: '90762',
  items: [
    {
      name: 'Áo Thun',
      weight: 100,
      quantity: 2,
      code: '0010',
    },
    {
      name: 'Áo Polo',
      weight: 150,
      quantity: 2,
      code: '0020',
    },
  ],
  weight: 250,
  length: 10,
  cod_amount: 20000,
  insurance_value: 15000,
  required_note: 'CHOTHUHANG',
  note: 'Ghi Chú',
  payment_type_id: 2,
  cod_failed_amount: 11000,
  service_type_id: 2,
  service_id: 0,
};
