//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHSTShipping.Infrastructure.Resources.ProjectResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GHSTShipping.Infrastructure.Resources.ProjectResources.EmailTemplate", typeof(EmailTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctypehtml&gt;&lt;html lang=vi&gt;&lt;meta charset=UTF-8&gt;&lt;meta content=&quot;width=device-width,initial-scale=1&quot;name=viewport&gt;&lt;title&gt;Yêu cầu đặt lại mật khẩu&lt;/title&gt;&lt;body style=font-family:Arial,sans-serif;background-color:#f4f4f4;margin:0;padding:0;color:#333&gt;&lt;div style=width:100%;padding:20px&gt;&lt;div style=&quot;max-width:600px;margin:0 auto;background-color:#fff;padding:30px;border-radius:10px;box-shadow:0 0 10px rgba(0,0,0,.1)&quot;&gt;&lt;h2 style=color:#333;font-size:24px;margin-bottom:20px&gt;Yêu cầu đặt lại mật khẩu&lt;/h2&gt;&lt;p style=font- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VI_RESET_PASSWORD {
            get {
                return ResourceManager.GetString("VI_RESET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctypehtml&gt;&lt;html lang=vi&gt;&lt;meta charset=UTF-8&gt;&lt;meta content=&quot;width=device-width,initial-scale=1&quot;name=viewport&gt;&lt;title&gt;Đặt Mật Khẩu Mới&lt;/title&gt;&lt;body style=font-family:Arial,sans-serif;background-color:#f4f4f4;margin:0;padding:0;color:#333&gt;&lt;div style=width:100%;padding:20px&gt;&lt;div style=&quot;max-width:600px;margin:0 auto;background-color:#fff;padding:30px;border-radius:10px;box-shadow:0 0 10px rgba(0,0,0,.1)&quot;&gt;&lt;h2 style=color:#333;font-size:24px;margin-bottom:20px&gt;Chào mừng bạn đến với chúng tôi!&lt;/h2&gt;&lt;p style=font- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VI_SET_PASSWORD {
            get {
                return ResourceManager.GetString("VI_SET_PASSWORD", resourceCulture);
            }
        }
    }
}
